# Generated by Django 3.2.9 on 2021-12-25 08:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMyEcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=100, null=True)),
                ('About', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='A Customer', max_length=150)),
                ('About', models.CharField(max_length=150, null=True)),
                ('Stars', models.CharField(default='⭐⭐⭐⭐⭐', max_length=5)),
                ('Review', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Desc', models.TextField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Stock', models.CharField(max_length=120, null=True)),
                ('Discount', models.IntegerField(null=True)),
                ('in_stock', models.BooleanField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, default='Your location', max_length=200, null=True)),
                ('Country', models.CharField(blank=True, default='Your location', max_length=100, null=True)),
                ('State', models.CharField(blank=True, default='Your location', max_length=100, null=True)),
                ('Pincode', models.CharField(blank=True, default='Your location', max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Logo', models.ImageField(default='static/seller/logo/default_logo.png', upload_to='')),
                ('Seller_Name', models.CharField(max_length=200, null=True)),
                ('Seller_PhoneNo', models.CharField(max_length=200, null=True)),
                ('Seller_Email', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150, null=True)),
                ('About', models.CharField(max_length=150, null=True)),
                ('Review', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.seller'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(blank=True, default=1, max_length=200, null=True)),
                ('Quantity', models.CharField(blank=True, default=1, max_length=200, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('PaymentStatus', models.BooleanField(default=0)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.seller')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='GuestCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Img', models.ImageField(blank=True, null=True, upload_to='')),
                ('Phone_No', models.CharField(max_length=100, null=True)),
                ('e_verify', models.BooleanField(default=0)),
                ('p_verify', models.BooleanField(default=0)),
                ('is_seller', models.BooleanField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
