# Generated by Django 3.2.9 on 2021-12-03 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='upload/category_img')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Img', models.ImageField(null=True, upload_to='upload/Profile_img')),
                ('Phone_No', models.CharField(max_length=100, null=True)),
                ('e_verify', models.BooleanField(default=0)),
                ('p_verify', models.BooleanField(default=0)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='A Customer', max_length=150)),
                ('About', models.CharField(max_length=150, null=True)),
                ('Stars', models.IntegerField(default=0)),
                ('Review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='upload/product_img')),
                ('Desc', models.TextField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Discount', models.IntegerField(null=True)),
                ('Active', models.BooleanField(default=1)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(max_length=100, null=True)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.product')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.orderstatus')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
