# Generated by Django 3.2.9 on 2021-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='CategoryImage'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='User_Img',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImage'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Business_Logo',
            field=models.ImageField(default='static/seller/logo/default_logo.png', upload_to='SellerLogo'),
        ),
    ]
