# Generated by Django 3.2.9 on 2021-12-04 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MY_Ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Active',
            new_name='in_stock',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Name', models.CharField(max_length=200, null=True)),
                ('Seller_PhoneNo', models.CharField(max_length=200, null=True)),
                ('Seller_Email', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150, null=True)),
                ('About', models.CharField(max_length=150, null=True)),
                ('Review', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='From',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.seller'),
            preserve_default=False,
        ),
    ]
