# Generated by Django 3.2.9 on 2021-12-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MY_Ecom', '0002_auto_20211204_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='State',
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_Ecom.seller')),
            ],
        ),
    ]
