# Generated by Django 3.2.9 on 2021-12-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0003_auto_20211204_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='Address',
            field=models.CharField(blank=True, default='Your location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Country',
            field=models.CharField(blank=True, default='Your location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Pincode',
            field=models.CharField(blank=True, default='Your location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='State',
            field=models.CharField(blank=True, default='Your location', max_length=100, null=True),
        ),
    ]
