# Generated by Django 3.2.9 on 2021-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0004_auto_20211204_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Business_Logo',
            field=models.ImageField(default='seller/logo/default_logo.png', upload_to='seller/logo'),
        ),
    ]
