# Generated by Django 3.2.9 on 2021-12-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0006_alter_seller_business_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller_Address',
        ),
    ]
