# Generated by Django 3.2.9 on 2021-12-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0007_delete_seller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Business_Logo',
            field=models.ImageField(default='upload/seller/logo/default_logo.png', upload_to='upload/seller/logo'),
        ),
    ]
