# Generated by Django 3.2.9 on 2021-12-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0008_alter_seller_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='upload/product_img/'),
        ),
    ]
