# Generated by Django 3.2.9 on 2021-12-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/category_img/'),
        ),
    ]
