# Generated by Django 3.2.9 on 2021-12-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0012_guestcart_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
