# Generated by Django 3.2.9 on 2021-12-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0013_customer_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='Stars',
            field=models.CharField(default='⭐⭐⭐⭐⭐', max_length=5),
        ),
    ]
