# Generated by Django 3.2.9 on 2021-12-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0014_alter_customer_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcart',
            name='Quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='usercart',
            name='Quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
