# Generated by Django 3.2.9 on 2021-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0015_auto_20211212_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcart',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercart',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
