# Generated by Django 3.2.9 on 2021-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0016_auto_20211212_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcart',
            name='Discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercart',
            name='Discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
