# Generated by Django 3.2.9 on 2021-12-13 08:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0017_auto_20211212_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMyEcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
