# Generated by Django 3.2.9 on 2021-12-13 08:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0018_aboutmyecom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=100, null=True)),
                ('About', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
