# Generated by Django 3.2.9 on 2021-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0019_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PaymentStatus',
            field=models.BooleanField(default=0),
        ),
    ]
