# Generated by Django 3.2.9 on 2021-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0021_alter_order_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='First_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
