# Generated by Django 3.2.9 on 2021-12-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_Ecom', '0022_auto_20211218_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PhoneNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
